#include <iostream>
using namespace std;

main (){
int nim[6]= {1, 2, 3, 4, 5, 6};
cout<<"Nama : M. ANDRE SOPIAN VIKTA"<<endl;
cout<<"NIM : F1B019086"<<endl;
cout<<"Kelompok : 18"<<endl;
cout << "Nim ke-1 adalah " << nim[0] << endl;
cout << "Nim ke-2 adalah " << nim[1] << endl;
cout << "Nim ke-3 adalah " << nim[2] << endl;
cout << "Nim ke-4 adalah " << nim[3] << endl;
cout << "Nim ke-5 adalah " << nim[4] << endl;
cout << "Nim ke-6 adalah " << nim[5] << endl;

}
